### ISSUE TITLE
missing legend for scale dataseries

### ISSUE THREAD

**Issue by mferretti** [bjornd/jvectormap#102]
Hi 
I believe I am missing something here : I would like to paint a scale for a choropleth map. I can easily come up with the right map but I haven't figured out a way of painting the legend. Is there a way to do this or do I have to do it manually ?

**Comment by cvsakpal** [comment]
@bjornd The legend wasn't showing up for me either. I had an error in the console saying "Cannot read property 'extend' of undefined" on line 1562 viz. "this.legend = new jvm.Legend($.extend({" in the min.js file viz. "jquery-jvectormap-2.0.4.min.js".

I added "$ = jQuery;" on line 362.
The legend shows up properly now... I'm wondering if its the right way to solve the bug, coz I really don't want to meddle in ur code...
Please let me know if there is a better way to do it... thanks.
