### ISSUE TITLE
Dragging mouse outside of map breaks panning and clicking functionality

### ISSUE THREAD

**Issue by picobots** [bjornd/jvectormap#113]
There is a bug in the mouse dragging code in jVectorMap. When you mousedown to begin dragging the map to pan it, if your mouse goes outside of the map div and then you mouseup _outside of the map_, when you put your mouse back over the map it pans automatically even without the mouse held down. The only way to disable it is to click on the map, but that's not an ideal solution, since the user is often forced to click a country they didn't want.

I think the solution would be to put the mouseup event on the body/document instead of on the map itself, so that you catch the mouseup everywhere.

**Comment by josemora1** [comment]
Hi. I have the same problem. Please could You tell me where to find the solution? Thanks.
