### ISSUE TITLE
calculate the center of a region

### ISSUE THREAD

**Issue by mferretti** [bjornd/jvectormap#146]
I am currently facing the 'issue' of placing markers in the centroid of a region. After playing for a couple of hours with the library I found the way to get it via the SVG DOM getBBox like this : 

```
     vectorMap = mapHook.vectorMap('get', 'mapObject');
     regions=vectorMap.regions;
```

then using  this convenience function : 

 function getCentroid(selection) {
        var element = selection.node;
        bbox = element.getBBox();
        return [bbox.x + bbox.width/2, bbox.y + bbox.height/2];
}

with regions[region] as parameter. 

Could it be of some use to have the function within the library ? something like 
$('#mapHook').vectorMap('get', 'mapObject').centroid(regionName); ??

**Comment by Swiftkilla** [comment]
I copied this function into a standalong function and edited a few things to get the SVG element for BBox.

**Comment by Swiftkilla** [comment]
[https://github.com/bjornd/jvectormap/issues/146#issuecomment-66823899](url)
