### ISSUE TITLE
indian map downloadable on jvector website

### ISSUE THREAD

**Issue by mikakun** [bjornd/jvectormap#153]
it's not a plugin issue, but I guess you didn't mean to offer for download a "politically incorrect" map of India : the boundaries for Jammu&Kashmir state (JK) are wrong

I think in natural earth shape file, they have 2 or 3 theme for Kashmir because it is disputed (see this shot : http://kelsocartography.com/blog/wp-content/uploads/2009/06/kashmir_ne.png from this blog http://kelsocartography.com/blog/?p=2502 )

the political boundaries for JK are the one delimited by the red dotted line, not the one delimited by the dashed grey line (the one that were converted).

(In all honesty i have no clue how to read the shape file from natural earth and find out which theme to convert to get the JK region correct...)

**Comment by imrieladmin** [comment]
Hi mikakun,

We are facing same issue in India map. We are showing Worl map in that india map is wronge for the ame region. We suspect that below is JS is creating an issue.

jquery-jvectormap-world-mill-en.js


Can you please previde us the fix in the above js if possible?

We will really appreciate your help!
Thanks in advance.

**Comment by mikakun** [comment]
that js above shows the correct india map, not the correct india map within a world map, you'll have to go the gis way to have a correct world map with a correct india without any overlapping.

**Comment by imrieladmin** [comment]
Thanks for the quick reply mikakun.

Are you able to provide us the correct shape file of the world where India shows its perfect geographical area.
We have downloaded shape file from http://www.naturalearthdata.com/downloads/ but it seems that in each shape file its not correct.

Moreover, we do not know much about GIS and phython, we are using jvectormap API world map (http://jvectormap.com/) in asp.net project 
we would like to create a new world map with correct Indian locations by following instructions as per below site 

http://stackoverflow.com/questions/11068645/how-to-generate-a-new-map-for-jvectormap-jquery-plugin

we will appreciate if you can guide us further in this manner, as we are told to show correct map on public site.

Thanks,
Dhaval.

**Comment by mikakun** [comment]
I'm able but that'd take quite a lot of working time as there is india, 
china & pakistan shape files to update.

do you have budget & want a quote  or are you going to learn how to use 
a gis software ? it's not that complicate to pick up as for the python 
command to convert in svg.

let me know & we can arrange a paypal payment (not sure i'm coming India 
this year but i can give you some reference in Delhi & Varanasi)

**Comment by imrieladmin** [comment]
Hi Thanks For your reply,
Actually we are using current Jvector API which display India as wrong in world map,
We would like to change it, kindly, let us know what will be your charges and how much time it would take to create. As we need as soon as possible.
Moreover we would like to make sure that Singapore and HongKong is also visible with this vector map which is not with current API.
Once you confirm and we agree with your provided estimates, we will send you our used API files and screens etc, just to make sure that after replacing things will work fine.

**Comment by mikakun** [comment]
Hi & sorry for delay,

are u still in need ? can you write me to my email -> mic_schaller@yahoo.fr

**Comment by gagan-bansal** [comment]
@imrieladmin Once I had processed the world map (naturalearth data) with correct India boundary. No doubt, there is work involved as mentioned by @mikakun. I am thinking to upload it on github soon.

**Comment by gagan-bansal** [comment]
Here is the required shape file
http://sourceforge.net/projects/countriesshp/files/admin0-countries-50m/
for further clarification please contact me on gaganbansal123@gmail.com

**Comment by kunalkishoresharma** [comment]
Hi mikakun,
When I put your jvector india map js then my marker is not showing.
pls reply ASAP.

Thanks

**Comment by manjoo07** [comment]
Anyone found the corrected INDIA map, pls share the direct link file changes i need it badly for my application.

Thanks
