### ISSUE TITLE
jquery-jvectormap-world-mill-en.js jQuery closure

### ISSUE THREAD

**Issue by heddn** [bjornd/jvectormap#196]
The default world map isn't wrapped in jQuery closures so I get 'Uncaught TypeError: Cannot read property 'fn' of undefined' until I wrap the entire script with:

``` javascript
  (function ($) {
    $.fn.vectorMap('addMap', 'world_mill_en'..........
  })(jQuery);
```

**Comment by iamatulsingh** [comment]
![2017-04-02 22_35_57-](https://cloud.githubusercontent.com/assets/20820833/24589237/cf535f06-17f4-11e7-8a02-63624879cdca.png)
Still have problem with code

**Comment by fraballi** [comment]
Hi, have the same error using requirejs with angularjs.
jvectormap: 'bjornd/jvectormap#2.0.5'
jvectormap-maps: '1618033/jvectormap-maps#*' ('world_mill', without 'en') 

Does a converter file (don't know which to use) has to be included along the other dependencies?
