### ISSUE TITLE
Repeated use of setScale method does not correctly set scale

### ISSUE THREAD

**Issue by rosswintle** [bjornd/jvectormap#213]
Hi there,

I'm building a fairly complex map that displays different data depending on the value selected in a dropdown <select> box.

I'm using setScale to change the dataset and min and max colours used when the dataset selected changes.

It took me a while to work out how to do this - it doesn't seem to be documented and I may be doing it wrong.  Here's my code:

``` javascript
MyMapObject.series.regions[0].scale.setMin(newMin);
MyMapObject.series.regions[0].scale.setMax(newMax);
MyMapObject.series.regions[0].setValues( newMapData.values );
MyMapObject.series.regions[0].setScale(newMapDataScale);
```

The scale will sometimes be an array of three colours, and sometimes an array of two colours.

If I set the scale to be an array of three colours, say, [ #FF0000, #FFFFFF, #00FF00 ], and then, subsequently, set it to be an array of two colours, e.g. [ #FFFFFF, #00FF00 ], the third value remains in the scale!

The code that does this is in lib/color-scale.js and reads:

``` javascript
jvm.ColorScale.prototype.setScale = function(scale) {
  var i;

  for (i = 0; i < scale.length; i++) {
    this.scale[i] = jvm.ColorScale.rgbToArray(scale[i]);
  }
};
```

So, the question is, am I using the wrong method to change the colours, or should the setScale method clear the array before executing the for loop?

Thanks

**Comment by rimager** [comment]
Just came here to say thank you!
