### ISSUE TITLE
Regions with markers in them

### ISSUE THREAD

**Issue by thetom88** [bjornd/jvectormap#231]
Hello everyone and thank you for you amazing and useful work.
I have a problem, I'd like to style regions that have at least one marker in their territory.
How may I do it?

**Comment by attisan** [comment]
@bjornd I would be willing to contribute on this one. I have had a look into approaches on calculating the marker positions against the path-shapes but am stuck at that level as my guess is that this way will not work out being mobile (processor) friendly at all.

it is a pitty svg getEnclosureList only works for rectangles.

Could you give me a hint on this topic?
