### ISSUE TITLE
updating marker fill color in onMarkerClick event

### ISSUE THREAD

**Issue by gekidoslair** [bjornd/jvectormap#237]
Have my maps working great, but for the life of me I can't figure out how to update the marker that was clicked's color to indicate that it has been updated / modified.

I did see that you can set the marker as selectable, which is fine, but in that case, I then need to know whether that particular marker has been selected or not previously.

Basically, how do I access the 'marker' array from within the onMarkerClick event so that I can update / read / modify it?

The reason is that for each marker's click, I do an ajax call to the server to set a flag.  I need to be able to update the markers fill colors dynamically.

Thanx in advance,
Mike W

**Comment by mrhb** [comment]
> That would be something like: `map.markers[0].element.setStyle('fill', 'red');`. Actually it's not a common behaviour, that's why it was not document.

how maybe this works for multimaps?
