### ISSUE TITLE
Windows8 touch event support

### ISSUE THREAD

**Issue by brouckaertd** [bjornd/jvectormap#244]
This issue (https://github.com/bjornd/jvectormap/issues/4) was about the integration of touch events on devices which support them.

It works on Android, but it doesn't seem to work in Windows phone and in Windows 8.

It would be handy if Windows 8 would be supported.

**Comment by hexcross** [comment]
Awesome plugin!  But this mobile issues is annoying.. it would be amazing if someone fix it :-)
