### ISSUE TITLE
Missing countries on the worldmap

### ISSUE THREAD

**Issue by meghuizen** [bjornd/jvectormap#254]
Thanks for creating this wonderful plugin. It creates wonderfull options.

I hover do miss some countries on the world map. These ones I miss:
  Bahrain (BH)
  Comoros (KM)
  Maldives (MV)

I can image why they are not included, because of the size. But it would be nice if they'd be included. Is it possible for them to be included?

**Comment by mohsen200013** [comment]
You can add the below lines to jquery-jvectormap-world-mill.js file for some of the missing countries

    "BH":  {"path": "M548 215 L549 215 L549 216 L548 216 Z", "name": "Bahrain"},
    "MV":  {"path": "M622 291 L624 291 L624 293 L622 293 Z", "name": "Maldives"},
    "SC":  {"path": "M564 301 L566 301 L566 303 L564 303 Z", "name": "Seychelles"},
    "MU":  {"path": "M571 347 L573 347 L573 349 L571 349 Z", "name": "Mauritius"},
    "SG":  {"path": "M680 280 L682 280 L682 282 L680 282 Z", "name": "Singapore"},
    "PW":  {"path": "M779 260 L781 260 L781 262 L779 262 Z", "name": "Palau"}
