### ISSUE TITLE
ie8 problems

### ISSUE THREAD

**Issue by wollowizard** [bjornd/jvectormap#260]
in ie8 for me countries don't get colored. Moreover every time I hover over a country, the following is written to the console:

SCRIPT438: Object doesn't support this property or method 
jquery-jvectormap-1.2.2.min.js, line 266 character 10

this is the content of line 266
this.node[e] = t

I solved in this way:

}, jvm.VMLElement.prototype.applyAttr = function (e, t) {
        //if(e!='scale')
        	this.node[e] = t

because I noticed that the problem happened just when applying the attribute scale.

Any idea what it could be?

**Comment by bjornd** [comment]
IE8 is not actively supported anymore.
