### ISSUE TITLE
Clear selected regions

### ISSUE THREAD

**Issue by farald** [bjornd/jvectormap#296]
Im trying to clear selected regions of single select map.

map.clearSelectedRegions();
Does not seem to do anything.

map.setSelectedRegions() without parameter throws an 

Uncaught TypeError: Cannot read property 'element' of undefined

How can I do this?
Thanks!

**Comment by fosskers** [comment]
`map.clearSelectedRegions()` works for me, but ironically using `setSelectedRegion()` on a selected region doesn't deselect it.
