### ISSUE TITLE
Is there a way to increase zoom rate while scrolling ?

### ISSUE THREAD

**Issue by anupamkumar** [bjornd/jvectormap#301]
I could not find it in the documentation so far. zoomStep does not effect zoom rate while using the scroll wheel.

**Comment by andi1984** [comment]
+1. Please provide an option for that.

**Comment by bjornd** [comment]
There is a related fix for that in develop https://github.com/bjornd/jvectormap/commit/0962b8ddbc10803adac4c083f6bcf1306c17e6b2. Hotfix will be released soon.

**Comment by fosskers** [comment]
+1 This would be very good to have.

**Comment by bjornd** [comment]
See bbb314c5298772ea232994b3e80d6d1a9b5d6de7
