### ISSUE TITLE
Lakshadweep is missing from India map

### ISSUE THREAD

**Issue by trolling42** [bjornd/jvectormap#304]
A set of islands in the Arabian sea that are part of India are missing from the map.

**Comment by Robinson7D** [comment]
Creating a separate ticket for each region that you find missing should be avoided. A single ticket could outline the various issues that you have with the India map.

A better option still would be to create a Pull Request with an updated map file, explaining what was fixed. One map source is http://www.naturalearthdata.com/ , if their map data is not sufficient then you should try to find another credible source. This library makes it simple to import map files for your project.

**Comment by trolling42** [comment]
@Robinson7D Yeah thanks. I thought since the issues were separate, I'd create separate issues for each of them. Will try to find a source to resolve this.
