### ISSUE TITLE
Fixed Marker Size

### ISSUE THREAD

**Issue by ParallaxStudios** [bjornd/jvectormap#307]
Hello,

We're developers creating a project using JVectorMap. One of the problems that we've been having involves marker sizes when zooming in. We want some of the markers to remain the same size no matter the zoom level. 

For example, if a marker stretches all the way across the state of Florida, it should stay stretched across the state of Florida and not get smaller as someone zooms in.

Is there a way to do this, or can an update be implemented?

**Comment by ParallaxStudios** [comment]
Nothing about this?

**Comment by danielcrisp** [comment]
I believe you can use the `onViewportChange: function (event, scale)` method documented here: http://jvectormap.com/documentation/javascript-api/jvm-map/ to listen for zoom changes and scale the markers accordingly. You'd probably need to keep references to your markers in an array.

Something along these lines - completely untested, not sure what value `scale` returns so will probably need some tweaking...

    // config    
    onViewportChange: function (event, scale) {
        // loop through your array of markers
        markers.forEach(function (marker) {
            var radius = defaultRadius * scale;
            // change the radius
            marker.element.node.setAttribute('r', radius);
        });
    }
