### ISSUE TITLE
India Map Missing states in Jvector Map website

### ISSUE THREAD

**Issue by vinithac** [bjornd/jvectormap#308]
Hi Team,

I'm not able to find correct India map. As few states near Kashmir are missing in the Maps provided in the website. Can you please send a link or file which contains correct India Map.I need to plot markers on India map.

This issue is almost related to 

https://github.com/bjornd/jvectormap/issues/153

But there I didn't found the working copy. Please share correct India MaP contains political boundaries near Jammu and Kashmir. I need JS file.

Thanks In advance.

**Comment by vinithac** [comment]
I need to plot markers on India map.

**Comment by vinithac** [comment]
Hi bjornd ...as you have close..I didn't find solution anywhere ...please provide working copy of indian map as I'm using jvector map for my application?

**Comment by bjornd** [comment]
I'm not developing data sources, I'm developing JS library, you can create your own map if you want. All tools are open-sources.

**Comment by vinithac** [comment]
Hi bjord thanks for you response. As mentioned in #153 issue ..there the user stated that map has been updated in github. I tried to search but invain.

**Comment by vinithac** [comment]
I've been struggling for this issue for about 2 months.The plugin is awesome and I've already integrated in to my application. Only thing is missing political boundaries in india map.

**Comment by jasmeetdd** [comment]
+1
I am facing the same issue. I cannot show a website on my website while showing parts of my country in other countries. It will be considered a disgrace here in India to show Kashmir as a part of Pakistan & China.
