### ISSUE TITLE
max and min values are not updated when region highlighting data changes 

### ISSUE THREAD

**Issue by erkanyildiz** [bjornd/jvectormap#313]
Inside `setValues` function of `data-series.js`,  `max` and `min` values are calculated on the first run, and never updated again as they are NOT `undefined` anymore:

`      if (typeof this.params.min === 'undefined' || typeof this.params.max === 'undefined') {`
`        // min and/or max are not defined, so calculate them`

**Comment by bjornd** [comment]
This was made intentionally. You can call setMin or setMax method of scale to update them by hand.
