### ISSUE TITLE
[Feature] Disable certain regions/markers

### ISSUE THREAD

**Issue by julianxhokaxhiu** [bjornd/jvectormap#314]
Hi,

I'm trying to disable certain regions/markers when my map is loaded because for some of them I don't have data binded. So actually, I tryed to disable Hover, Select and Tooltip show using events.

Actually the only thing I miss is how to grey out (or make them disappearing at all using `opacity: 0`) them based on country code. Is it possible to it using some kind of event like:

```js
.vectorMap({
   // ...
   onRegionInit: function ( e, code ) {
      if ( code == 'US' ) e.preventDefault() // or something like this, should just make it not visible, not hoverable, not selectabled and no tooltips shown at all
   }
   // ...
})
```

Like `onRegionInit` could be identical the `onMarkerInit` event, to manage also markers.

Thanks in advice for any help!

**Comment by bjornd** [comment]
You can just create a data series to set color of disabled regions to specific value.

**Comment by julianxhokaxhiu** [comment]
Yeah, sorry forgot to update the issue. I solved exactly like that :) Thank you anyway
