### ISSUE TITLE
Scroll wheel zoom is far too slow

### ISSUE THREAD

**Issue by lyml** [bjornd/jvectormap#317]
Zooming with the scrool wheel is painfully slow. By changing src/map.js:331 to:

zoomStep = Math.pow(1.03, event.deltaY);

I got a more acceptable speed, this issue is described in this this stack-overflow post:

http://stackoverflow.com/questions/27326531/jvectormap-scroll-speed-and-full-screen-issue

**Comment by fosskers** [comment]
Wasn't this already changed on a dev branch?

**Comment by bjornd** [comment]
It's even changed in master branch, I only need to deploy it.
