### ISSUE TITLE
[Suggestion] - Delay the "onMarkerClick" event triggering

### ISSUE THREAD

**Issue by Ninir** [bjornd/jvectormap#325]
Hey guys,

As saw in `src/map.js` on line 473:
```javascript
map.container.trigger(clickEvent, [code]);
```

this triggers the click event. However, the element is selected right after on line 480
```javascript
element.setSelected(!element.isSelected);
```

This is kind of odd as the triggering should be made after just to be consistent. What do you think of moving the triggering right after (thus bringing a potential break in some applications), or at least add another event just to handle this case?

**Comment by bjornd** [comment]
It's all done on purpose. Click event can be prevented to cancel element selection.

**Comment by Ninir** [comment]
@bjornd Well then ok. What about adding a post-selected, like "onMarkerClicked" then?
Having only the before is nice, having both is even more flexible.

**Comment by bjornd** [comment]
What is the use-case?

**Comment by Ninir** [comment]
When you click a marker, then calling this.getSelectedMarkers().
I know you can store markers in a var, then calling `markers[code]` from the method for a single marker. What if I want to get all the selected markers?

**Comment by bjornd** [comment]
You can just subscribe to 'markerSelected.jvectormap' event.
