### ISSUE TITLE
FEATURE REQUEST - Region Merge

### ISSUE THREAD

**Issue by luisalvarado** [bjornd/jvectormap#333]
An option to merge different regions visually so it looks as one whole region. A quick example is the UK map where, it shows all sub-countries of the United Kingdom but instead of showing England it shows the regions of England. So this option would merge all England regions into one and would only show one region named England.

This can also be useful when merging states, counties and more to show specific colors that show information regarding any topic (States or counties with healthier people, happier, better economically, etc..)

**Comment by Polyergic** [comment]
👍

**Comment by luisalvarado** [comment]
Just updating that I already created the England map with all merged areas which is the one being used right now on the site. So at least for this case we are good to go. But might be a good idea for the future.
