### ISSUE TITLE
Getting error while using converter.py only when longitude0 parameter is set to value 11.5

### ISSUE THREAD

**Issue by paritoshd** [bjornd/jvectormap#335]
Hi,

I'm getting the following error while converting .shp file to the equivalent js file.
Generating jquery-jvectormap-world-mill-en.js
Traceback (most recent call last):
  File "converter.py", line 300, in <module>
    converter.convert(paramsJson['output_file'])
  File "converter.py", line 171, in convert
    self.loadData()
  File "converter.py", line 107, in loadData
    self.loadDataSource( sourceConfig )
  File "converter.py", line 129, in loadDataSource
    p1 = transformation.TransformPoint(-180, 89)
  File "C:\Python27\lib\site-packages\osgeo\osr.py", line 709, in TransformPoint
    return _osr.CoordinateTransformation_TransformPoint(self, *args)
NotImplementedError: Wrong number of arguments for overloaded function 'CoordinateTransf
  Possible C/C++ prototypes are:
    TransformPoint(OSRCoordinateTransformationShadow *,double [3])
    TransformPoint(OSRCoordinateTransformationShadow *,double [3],double,double,double)

This only happens when i give a value to central_meridian (longitude0) to 11.5, i.e. other than 0 the default value.

This is my world.json
{
    "input_file": "ne_10m_admin_0_countries_lakes.shp",
    "output_file": "jquery-jvectormap-world-mill-en.js",
	"simplify_tolerance": 0.32,
	"buffer_distance": -0.3,
	"longitude0": 11.5,
    "projection": "mill"
}

If the longitude0 is 0, no error occurs, i get the converted file, correctly. But i do need this with 11.5 centralmeridian.

Can anyone please tell me what is wrong over here, any lib missing or what?
I'm using 32-bit python with gdal and its python bindings, shapely and its bindings.

Or atleast suggest an alternate solution with an older converter or etc.

In this link here http://jvectormap.com/documentation/gis-converter/
you guys have converted with 11.5 as longitude0, can you atleast tell me which version of coverter.py, gdal and its core, shapely was used, so i can get this done, if this bug is something library related.

Please guys help me out here, i'm at a deadline.

Thanks,
PD

**Comment by bjornd** [comment]
Looks like proj4 problem. Take a look here https://github.com/avalentino/gsdview/issues/89

**Comment by paritoshd** [comment]
Thanks for the quick reply, I didn't get any such proj4 error.
Anyway I still installed libproj4, set the installed path to my lib search path, still didn't work.


Please help
