### ISSUE TITLE
Selected regions stay selected on history.back

### ISSUE THREAD

**Issue by lepaff** [bjornd/jvectormap#338]
I´m having a map where you can click on the countries to get more information. Everything works fine but ...
On mobile devices (tested with android and ios phones) the selected area stays selected after i use the browser´s back button. The map then also executes the action on a country after the first tap (Actually you have to tap twice - once to select and once to execute the action) and activates the country. Next time you use the browser´s back button you already have two selected countries ...

**Comment by bjornd** [comment]
Any reason they should not be?

**Comment by lepaff** [comment]
Actually the last country could stay selected on using the browser´s back button. But on the next tap only the tapped country should be selected.

**Comment by bjornd** [comment]
If you refer to markers.html it uses browser localstorage to preserver selected state.
