### ISSUE TITLE
Firefox only error: ns_failure_error

### ISSUE THREAD

**Issue by JasonTheAdams** [bjornd/jvectormap#350]
I'm using jvectormap on a site: https://letsservetheworld.com/

For some reason, it works on every browser except Firefox, wherein I get an NS_FAILURE_ERROR from the jsvectormap.js file. It's at 2.0.2, currently, but I tried updating to 2.0.4 and it didn't help. I see it's not happening on the jvectormap.com site, but I was hoping I could get pointed in the right direction.

**Comment by saibotsivad** [comment]
@JasonTheAdams I'm having the same problem (using 2.0.3) did you ever find a solution?

Looks like it's something in the code:

```
jvm.SVGElement.prototype.getBBox = function(){
  return this.node.getBBox();
}
```

**Comment by JasonTheAdams** [comment]
@saibotsivad Obviously that was months ago, but if I recall correctly it was the fact that it was attempting to draw to the svg element while it had `display: none` applied to it, which apparently in Firefox is an error. I simply worked around the issue by avoiding hiding the element in this manner.
