### ISSUE TITLE
Converter Issues

### ISSUE THREAD

**Issue by aliciaduffy** [bjornd/jvectormap#352]
I'm trying to combine Canada provinces and US states into one map. 

I downloaded the NE shape file to the converter directory, and have a copied config set up to see if it works:
```
[{
  "name": "read_data",
  "file_name": "ne_10m_admin_1_states_provinces_lakes/ne_10m_admin_1_states_provinces_lakes.shp",
  "filter": "iso_a2 = \"CA\" AND iso_3166_2 IS NOT NULL"
},{
  "name": "write_data",
  "format": "jvectormap",
  "params": {
    "code_field": "iso_3166_2",
    "name_field": "name",
    "name": "ca"
  }
}]
```

i ran python processor.py input_file.json in terminal, but got this error: 
'ImportError: No module named booleano.parser'

I'm on a mac - I thought I had all the dependencies and can't figure out how to install this booleano.parser

**Comment by aliciaduffy** [comment]
Fixed!

**Comment by escael** [comment]
Hi, 
How did you fixed?
I have the same problem

**Comment by aliciaduffy** [comment]
I had to run 'easy_install booleano'. 

I was never able to get processor.py working so I ended up using converter.py

**Comment by andy-ez** [comment]
Had a similar issue here, after installing booleano got this working by changing processor.py slightly. 

Changed line 13 from:
`from booleano.parser import Grammar, EvaluableParseManager, SymbolTable, Bind`

To:
```ruby
from booleano.parser import Grammar
from booleano.parser.core import EvaluableParseManager 
from booleano.parser.scope import SymbolTable, Bind
```

Also had to set the file_name key in the input json file.
