### ISSUE TITLE
ie8,ie7,ie6,dosen't see the region text(render)

### ISSUE THREAD

**Issue by YealZoy** [bjornd/jvectormap#360]
var map = new jvm.Map({
        map: "sy",
        container: $('#map'),
        maxLevel: 1,
        backgroundColor: "#fff",
        regionStyle: {
            initial: {
                "fill-opacity": 1,
                "stroke": "black",
                "stroke-width": 1
            },
            hover: {
                "fill-opacity": 0.8
            }
        },
        series: {
            regions: [{
                attribute: 'fill'
            }]
        },
        labels: {
            regions: {
                render: function(code) {
                    return $('#map').vectorMap('get', 'mapObject').getRegionName(code);
                },
                offsets: function(code) {
                    return {
                        'a10': [0, -35],
                        'a5':[-20,10],
                        'a7':[-20,20],
                        'a20':[20,0],
                        'a14':[0,46]
                    }[code];
                }
            }
        },
        onRegionTipShow: function(event, el, code) {
            el.html("<div class='tips_title'>" + map.getRegionName(code) + "</div>" + "<div class='tips_content'>数据值是" + data[code] + "</div>");
        }
    });

I'm so sorry ,my english is so poor,
I hope someone know me,

I write render function ,I test in ie9 & ie10 & chrome & firefox can see the lable,but ie8,ie7,ie6 cant't see the label on the browser,

**Comment by bjornd** [comment]
>but ie8,ie7,ie6 cant't see the label on the browser
This is by design, labels are not supported on ie8 and less as stated in documentation: "Plase note: static labels feature is not supported in Internet Explorer 8 and below."
