### ISSUE TITLE
Add image background for a region

### ISSUE THREAD

**Issue by AbstractFlame** [bjornd/jvectormap#365]
I like to add unique image background to every region in a map.
I have tried a lot of things, but they didn't work.

I see that: https://github.com/bjornd/jvectormap/issues/64

How does it work?

Thanks...

**Comment by bjornd** [comment]
See this example: http://jvectormap.com/examples/legends/. Check California and Texas. Is this what you want?

**Comment by AbstractFlame** [comment]
Yes... I saw that, but I like to use an image that is autoscale with the region and fill it. Is it possible?

**Comment by bjornd** [comment]
I don't think it will be a standard feature though you can always put some element with background under the map and bind its scale to the map scale changes.
