### ISSUE TITLE
How to make map responsive?

### ISSUE THREAD

**Issue by nicolagordon** [bjornd/jvectormap#399]
Hi, 

Is there some way for me to make my map responsive, or is there an updated version of JVectorMap that supports this?  It is unusable via my mobile device in it's current format - when holding my device in 'portrait' orientation only half the map can be seen since it doesn't resize.

I tried implementing a suggestion by @bjornd from a different post:
[https://github.com/bjornd/jvectormap/issues/273]
I tried calling setFocus (I describe my efforts on that post), but I wasn't able to get it working.

Can someone advise - any input would be great - thanks,
- Nicola

**Comment by bjornd** [comment]
To make a jVectorMap responsive you off course need to make its container responsive. From you example in #273 I see you container has fixed width and height. Just deal with container first, jVectorMap component will catch up with it.
