### ISSUE TITLE
Marker icons cause jQuery error

### ISSUE THREAD

**Issue by Rosslington** [bjornd/jvectormap#448]
I'm trying to replace the standard circles with images/icons.

I've tried using "markerStyle: { image: "src" }" and the image/label combo explained in the examples page. 

Both return the same error: jQuery.Deferred exception: img.error is not a function whenImageLoaded

**Comment by Gerben321** [comment]
Same. I've read it's because this outdated plugin is not compatible with jQuery 3. Sadly downgrading to 2.x is not an option for me.

**Comment by Rosslington** [comment]
> 
> 
> Same. I've read it's because this outdated plugin is not compatible with jQuery 3. Sadly downgrading to 2.x is not an option for me.

This is fixed in the develop build - https://github.com/bjornd/jvectormap/tree/develop
