### ISSUE TITLE
jVectorMap won't load if using jQuery.noConflict()

### ISSUE THREAD

**Issue by localstatic** [bjornd/jvectormap#82]
The map doesn't appear to be able to load when using jQuery's noConflict(). I have created a basic test page to illustrate. This page is based on the example on the tutorials/getting-started page on the site. This example doesn't work as-is, but if you remove the jQuery.noConflict() call, it works. 

I'm using jQuery v1.4.4 (as distributed with Drupal 7.15).
Tested in Chrome 21.0.1180.82 and FireFox 14.0.1.

Example page:

```
<!DOCTYPE html>
<html>
    <head>
        <title>jVectorMap demo</title>
        <link rel="stylesheet" href="jquery-jvectormap-1.0.css" type="text/css" media="screen"/>
        <script src="jquery.js"></script>
        <script src="jquery-jvectormap-1.0.min.js"></script>
        <script src="jquery-jvectormap-world-mill-en.js"></script>
    </head>
    <body>
        <div id="world-map" style="width: 600px; height: 400px"></div>
        <script>
            jQuery(function(){
                jQuery.noConflict();
                jQuery('#world-map').vectorMap();
            });
        </script>
    </body>
</html>
```

Error (from Chrome):

```
Uncaught TypeError: Cannot call method 'extend' of undefined jquery-jvectormap-1.0.min.js:7
jvm.WorldMap jquery-jvectormap-1.0.min.js:7
e.fn.vectorMap jquery-jvectormap-1.0.min.js:7
(anonymous function) index.html:15
b.extend.ready jquery.js:30
u
```

**Comment by kressly** [comment]
I am facing the same issue. It is not working in no conflict mode. How to solve this please ?

**Comment by innovatorydevelopment** [comment]
![image](https://user-images.githubusercontent.com/57936825/76724534-441df200-6771-11ea-913d-2ca1f6a0cccb.png)

**Comment by davidzarzoso** [comment]
Hi, @innovatorydevelopment did u solve it? I'm struggle whit the same problem

**Comment by CyberCyclone** [comment]
I just used `$.noConflict()` and then in the jVectorMap file, replaced all the `$` with `jQuery`. The file should be using jQuery and then allow an alias for $.
