### ISSUE TITLE
Getting Started code not working

### ISSUE THREAD

**Issue by essenceofire** [bjornd/jvectormap#85]
I copied and pasted the first part of the getting started code exactly from the website but I keep getting
 Uncaught ReferenceError: jvm is not defined in Chrome and Firefox on lines 32 and 39

And the map does not display. It is literally word for word the same as the one posted on the website so I know I didn't type anything incorrectly or change anything.  Thank you!

**Comment by stormhillmedia** [comment]
the jsfiddle example does not work
