### ISSUE TITLE
Western Sahara & Morocoo

### ISSUE THREAD

**Issue by coderintherye** [bjornd/jvectormap#93]
"On the map, you have the territory of Western Sahara as part of Morocco. Neither the UN, African Union or most governments (incl. the US and Canada) recognize Morocco's claim on Western Sahara."

Some feedback we received. Looking at the World Bank and UN websites this seems to check out. 

Could we separate these two entities?

**Comment by staceypee** [comment]
Hello,
Has anyone taken a stab at this?  The data above from 2012 no longer seems to be an accurate reflection of the current version of the world map (it seems to be about 100 px northeast of where it should be)?  

I don't see any other way to easily modify these paths-- I'd love to split Morocco and Western Sahara.

**Comment by llcool** [comment]
Hi staceypee,

I have Morocco and Western Sahara. I think I generate to files (data) from (somewhere)?
Have a look at my map here: http://3dairspace.org.uk/airspace.html

**Comment by indysp80** [comment]
Hi,

Is somebody have a version of Morocco and Western Sahara splited, like this map ? 
http://indicators.ohchr.org/

**Comment by ELOUASTANI** [comment]
This is the javascript vectormap of all Morocco, enjoy it :)

"MA": {"path": "M 406.28906 191.66016 L 405.57031 193.25 L 403.90039 196.17969 L 403.80078 196.28906 L 401.93945 197.44922 L 399.46094 198.7207 L 397.93945 200.50977 L 397.60938 201.94922 L 396.68945 204.25 L 397.30078 207.58984 L 397.23047 207.84961 L 395.14062 210.13086 L 393.83984 210.90039 L 391.89062 212.73047 L 391.7207 212.81055 L 389.48047 213.09961 L 388.2793 214.08984 L 386.7207 216.80078 L 386.60938 216.91016 L 385.00977 217.84961 L 384.17969 219.36914 L 384.09961 220.83008 L 383.43945 222.38086 L 383.30078 222.5293 L 382.50977 222.92969 L 381.17969 224.53906 L 380.38086 226.2793 L 380.51953 227.08008 L 380.48047 227.28906 L 379.66016 228.66016 L 378.85547 229.2832 L 378.85547 229.28125 L 378.84961 229.28125 C 378.84998 229.28325 378.84917 229.28511 378.84961 229.28711 L 378.76367 229.35547 C 378.73997 229.36707 378.71837 229.38168 378.69727 229.39648 L 378.68359 229.40234 C 378.68277 229.40334 378.68264 229.40525 378.68164 229.40625 C 378.67564 229.41125 378.66556 229.41322 378.66016 229.41992 L 378.67773 229.41211 C 378.67473 229.41711 378.67292 229.42409 378.66992 229.42969 L 378.66602 229.43164 C 378.66502 229.43664 378.66411 229.44207 378.66211 229.44727 C 378.65911 229.45327 378.65534 229.45864 378.65234 229.46484 C 378.65134 229.46884 378.64944 229.47161 378.64844 229.47461 L 378.65234 229.47266 C 378.64834 229.48516 378.64533 229.49737 378.64062 229.50977 C 378.63362 229.53147 378.62514 229.55387 378.61914 229.57617 C 378.61614 229.59797 378.61117 229.61933 378.60547 229.64062 C 378.60147 229.65742 378.5948 229.67235 378.5918 229.68945 C 378.5898 229.70475 378.58984 229.72093 378.58984 229.73633 C 378.58884 229.75263 378.58408 229.76916 378.58008 229.78516 C 378.57808 229.80226 378.56945 229.81768 378.56445 229.83398 C 378.55645 229.85368 378.54892 229.87148 378.54492 229.89258 C 378.54192 229.91008 378.53716 229.92771 378.53516 229.94531 C 378.52916 229.96221 378.52253 229.97819 378.51953 229.99609 C 378.51453 230.01299 378.51077 230.03123 378.50977 230.04883 C 378.50277 230.06863 378.49909 230.08848 378.49609 230.10938 C 378.49509 230.12797 378.49028 230.14762 378.48828 230.16602 C 378.48628 230.18382 378.48438 230.20075 378.48438 230.21875 C 378.48415 230.23585 378.48435 230.25243 378.48438 230.26953 C 378.48449 230.29093 378.4844 230.31258 378.48438 230.33398 C 378.4844 230.35728 378.48442 230.381 378.48438 230.4043 C 378.48638 230.4253 378.47861 230.44464 378.47461 230.46484 C 378.47261 230.48704 378.46859 230.5078 378.46289 230.5293 C 378.45789 230.5526 378.44836 230.57436 378.44336 230.59766 C 378.43536 230.62606 378.42597 230.65509 378.41797 230.68359 C 378.41197 230.70709 378.4092 230.73166 378.4082 230.75586 C 378.4012 230.77316 378.39753 230.79019 378.39453 230.80859 C 378.39253 230.82569 378.39258 230.84217 378.39258 230.85938 C 378.39258 230.87717 378.39644 230.89626 378.39844 230.91406 C 378.40044 230.93476 378.39739 230.95596 378.40039 230.97656 C 378.40939 230.99556 378.41587 231.01496 378.42188 231.03516 C 378.42787 231.05116 378.43227 231.06912 378.44727 231.07812 C 378.51437 231.09623 378.54977 231.03573 378.57227 230.99023 C 378.58127 230.97633 378.58675 230.96021 378.59375 230.94531 C 378.59875 230.92961 378.60537 230.91484 378.60938 230.89844 C 378.61237 230.87794 378.61935 230.85839 378.62305 230.83789 C 378.62705 230.81749 378.62907 230.79529 378.63477 230.77539 C 378.64077 230.75679 378.64158 230.73805 378.64258 230.71875 C 378.64258 230.70025 378.6423 230.68176 378.64844 230.66406 C 378.65344 230.64616 378.65646 230.62738 378.66016 230.60938 C 378.66216 230.59207 378.66813 230.5786 378.67383 230.5625 C 378.67983 230.5463 378.68386 230.52982 378.69336 230.51562 C 378.70036 230.50362 378.70494 230.49092 378.71094 230.47852 C 378.71694 230.46322 378.72347 230.44859 378.73047 230.43359 C 378.73447 230.41809 378.74305 230.40377 378.74805 230.38867 C 378.74905 230.38467 378.7489 230.3797 378.75 230.375 L 379.1582 230.375 L 379.1582 230.36914 L 383.25781 230.36914 L 383.25781 230.37891 L 386.52344 230.37891 L 386.52344 230.375 L 388.24805 230.38086 L 387.81836 226.91992 L 387.83789 226.75977 L 388.44727 225.40039 L 388.6875 225.23047 L 390.75781 225.01953 L 390.73828 223.49219 L 390.73828 218.30078 L 397.75586 218.30078 L 398.89844 218.32031 L 398.89844 218.30078 L 398.92773 218.30078 L 398.92773 213.50977 L 398.9082 210.59961 L 399.07812 210.33008 L 403.11719 208.32031 L 405.67773 207.88086 L 407.60742 207.18945 L 408.50781 205.89062 L 408.64844 205.7793 L 411.38867 204.75977 L 411.48828 202.91016 L 411.73828 202.63086 L 413.09766 202.40039 L 414.16797 201.42969 L 414.32812 201.35938 L 417.4375 200.91992 L 417.74805 200.18945 L 417.24805 199.74023 L 417.1582 199.59961 L 416.29883 196.64062 L 416.14844 194.92969 L 415.31836 193.33008 L 414.34766 193.30078 L 411.79883 192.67969 L 409.46875 192.86914 L 409.25781 192.81055 L 407.82812 191.66992 L 406.28906 191.66016 z", "name": "Morocco"},
